/**
 * FILE: Telemetry.proto
 * BRIEF: Telemetry data from various boards (Data Management Board, Sensor Observation Board, Plumbing Bay Board, etc.)
 * AUTHOR: Christopher Chan (cjchanx) and Shanna Hollingworth (shanna1408)
 */
syntax = "proto3";
package Proto;
import "CoreProto.proto";

/* This acts as the telemetry wrapper message for all SOAR Telemetry Messages.
 * Telemetry messages are considered best-effort NON-CRITICAL messages, and are (currently) not guaranteed to be received (no ACK or Sequence Number)
 */
message TelemetryMessage {
    // Message Path
    Node source = 1; // This is the source of the message (the node that sent the message)
    Node target = 2; // This is the destination of the message, if this is a broadcast message, this should be set to NODE_ANY

    // Message Data
    oneof message {
        Gps gps = 3;  
        Baro baro = 4;
        Imu imu = 5;
        Flash flashState = 7;
        LPbbPressure lpbbPressure = 9;
        LPbbTemperature lpbbTemperature = 10;
        UPbbPressure upbbPressure = 11;
        UPbbTemperature upbbTemperature = 12;
        ValveControlStatus valveControlStatus = 13;
    }
}

/* DMB -> RCU Messages ---------------------------------------------------------------- */
message Gps{
    CoordinateType latitude = 1;   // latitude of rocket
    CoordinateType longitude = 2;  // longitude of rocket

    AltitudeType antenna_altitude = 3; // altitude of antenna
    AltitudeType geo_id_altitude = 4; // altitude of geoid
    AltitudeType total_altitude = 5;   // total altitude of rocket

    uint32 time = 6;        // time of message
}

message CoordinateType {
    int32 degrees = 1; 
    int32 minutes = 2;
}

message AltitudeType {
    int32 altitude = 1;
    int32 unit = 2;
}

message Baro{
    int32 baro_pressure = 1;    // barometer pressure
    int32 baro_temperature = 2; // barometer temperature
}

message Imu{
    int32 accel_x = 1;  // x direction of acceleration
    int32 accel_y = 2;  // y direction of acceleration
    int32 accel_z = 3;  // z direction of acceleration

    int32 gyro_x = 4;   // x direction of gyroscope
    int32 gyro_y = 5;   // y direction of gyroscope
    int32 gyro_z = 6;   // z direction of gyroscope
}

message Flash {
    uint32 sector_address = 1;
    uint32 logging_rate = 2;
}

/* PBB -> DMB Messages ---------------------------------------------------------------- */

message LPbbPressure {
    int32 pt18_pressure = 1;
    int32 pt19_pressure = 2;
}

message LPbbTemperature {
    int32 tc11_temperature = 1;
    int32 tc12_temperature = 2;
}

message UPbbPressure {
    int32 pt15_pressure = 1;
    int32 pt16_pressure = 2;
    int32 pt17_pressure = 3;
}

message UPbbTemperature {
    int32 tc10_temperature = 1;
}

message ValveControlStatus {
    bool sol_10_open = 1;
    bool sol_11_open = 2;
    bool sol_12_open = 3;
    bool sol_13_open = 4;
    bool sol_14_open = 5;
}